services:
  frontend:
    image: ${DEMOMO_REGISTRY:-demomo}/frontend:${TAG:-latest}
    container_name: demomo-frontend
    ports:
      - "4200:4200"
    networks:
      - demomo-network
    depends_on:
      - backend
      - model-text-generation
      - model-character-creation
      - model-library-service

  backend:
    image: ${DEMOMO_REGISTRY:-demomo}/backend:${TAG:-latest}
    container_name: demomo-backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=mysql
      - DB_PORT=3306
    networks:
      - demomo-network
    depends_on:
      mysql:
        condition: service_healthy

  model-text-generation:
    image: ${DEMOMO_REGISTRY:-demomo}/model-text-generation:${TAG:-latest}
    container_name: demomo-model-text-generation
    ports:
      - "5000:5000"
    environment:
      - MONGO_ATLAS=${MONGO_ATLAS}
      - DB_NAME_MONGO=${DB_NAME_MONGO}
      - GEMINI_API_KEY1=${GEMINI_API_KEY1}
    networks:
      - demomo-network

  model-character-creation:
    image: ${DEMOMO_REGISTRY:-demomo}/model-character-creation:${TAG:-latest}
    container_name: demomo-model-character-creation
    ports:
      - "6500:6500"
    environment:
      - MONGO_ATLAS=${MONGO_ATLAS}
      - DB_NAME_MONGO=${DB_NAME_MONGO}
    networks:
      - demomo-network

  model-library-service:
    image: ${DEMOMO_REGISTRY:-demomo}/model-library-service:${TAG:-latest}
    container_name: demomo-model-library-service
    ports:
      - "7625:7625"
    environment:
      - MONGO_ATLAS=${MONGO_ATLAS}
      - DB_NAME_MONGO=${DB_NAME_MONGO}
    volumes:
      - ./logs:/app/logs
    networks:
      - demomo-network

  mysql:
    image: ${DEMOMO_REGISTRY:-demomo}/mysql:${TAG:-latest}
    container_name: demomo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - demomo-network
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}", "-e", "SELECT 1;"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
    name: demomo-mysql-data

networks:
  demomo-network:
    external: true

secrets:
  db_password:
    external: true
  django_secret:
    external: true