services:
  frontend:
    image: ${DEMOMO_REGISTRY}:frontend-${DEMOMO_TAG}
    container_name: demomo-frontend
    ports:
      - "4200:4200"
    networks:
      - demomo-network
    depends_on:
      - backend
      - model-text-generation
      - model-character-creation
      - model-library-service

  backend:
    image: ${DEMOMO_REGISTRY}:backend-${DEMOMO_TAG}
    container_name: demomo-backend
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=mysql
      - DB_PORT=${DB_PORT}
      - MONGO_ATLAS=${MONGO_ATLAS}
      - DB_NAME_MONGO=${DB_NAME_MONGO}
      - GEMINI_API_KEY1=${GEMINI_API_KEY1}
    networks:
      - demomo-network
    depends_on:
      mysql:
        condition: service_healthy

  model-text-generation:
    image: ${DEMOMO_REGISTRY}:text-gen-${DEMOMO_TAG}
    container_name: demomo-model-text-generation
    ports:
      - "5000:5000"
    environment:
      - MONGO_ATLAS=${MONGO_ATLAS}
      - DB_NAME_MONGO=${DB_NAME_MONGO}
      - GEMINI_API_KEY1=${GEMINI_API_KEY1}
    networks:
      - demomo-network

  model-character-creation:
    image: ${DEMOMO_REGISTRY}:char-create-${DEMOMO_TAG}
    container_name: demomo-model-character-creation
    ports:
      - "6500:6500"
    environment:
      - MONGO_ATLAS=${MONGO_ATLAS}
      - DB_NAME_MONGO=${DB_NAME_MONGO}
    networks:
      - demomo-network

  model-library-service:
    image: ${DEMOMO_REGISTRY}:library-${DEMOMO_TAG}
    container_name: demomo-model-library-service
    ports:
      - "7625:7625"
    environment:
      - MONGO_ATLAS=${MONGO_ATLAS}
      - DB_NAME_MONGO=${DB_NAME_MONGO}
    volumes:
      - ./logs:/app/logs
    networks:
      - demomo-network

  mysql:
    image: ${DEMOMO_REGISTRY}:mysql-${DEMOMO_TAG}
    container_name: demomo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - demomo-mysql:/var/lib/mysql
    networks:
      - demomo-network
    healthcheck:
      test: mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  demomo-mysql:

networks:
  demomo-network:
    external: true