services:
  frontend:
    image: nuriz1996/demomo:frontend-${TAG:-go}
    container_name: demomo-frontend
    ports:
      - "4200:4200"
    networks:
      - demomo-network
    depends_on:
      - backend
      - model-text-generation
      - model-character-creation
      - model-library-service

  backend:
    image: nuriz1996/demomo:backend-${TAG:-go}
    container_name: demomo-backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - SECRET_KEY=django-insecure-s&49kpnt!ms0^9xg!1h3zovejldw!h9cic#@3ozg@^nly!msz(
      - DB_NAME=dnd
      - DB_USER=root
      - DB_PASSWORD=MYSQLnur1996##
      - DB_HOST=mysql
      - DB_PORT=3306
    networks:
      - demomo-network
    depends_on:
      mysql:
        condition: service_healthy

  model-text-generation:
    image: nuriz1996/demomo:text-gen-${TAG:-go}
    container_name: demomo-model-text-generation
    ports:
      - "5000:5000"
    env_file:
      - ./model/.env
    networks:
      - demomo-network

  model-character-creation:
    image: nuriz1996/demomo:char-create-${TAG:-go}
    container_name: demomo-model-character-creation
    ports:
      - "6500:6500"
    env_file:
      - ./model/.env
    networks:
      - demomo-network

  model-library-service:
    image: nuriz1996/demomo:library-${TAG:-go}
    container_name: demomo-model-library-service
    ports:
      - "7625:7625"
    env_file:
      - ./model/.env
    volumes:
      - ./logs:/app/logs
    networks:
      - demomo-network

  mysql:
    image: mysql:8.0
    container_name: demomo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: MYSQLnur1996##
      MYSQL_DATABASE: dnd
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - demomo-network
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-pMYSQLnur1996##", "-e", "SELECT 1;"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
    name: demomo-mysql-data

networks:
  demomo-network:
    external: true 