# Generated by Django 4.1.13 on 2024-08-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_pwd_user_str_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/default-prfle-pic/no_profile_pic.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
